In [10]:
      
               # ** Assignment questions :-
    
    
    
   #   1) Write a programe to combine a one & a 2-Dimensional Numpy Array.
    
    # programs:- 
    
    # importing Numpy package
import numpy as np

num_1d = np.arange(7)
print("One dimensional array:")
print(num_1d)

num_2d = np.arange(21).reshape(3,7)
print("\nTwo dimensional array:")
print(num_2d)

# Combine 1-D and 2-D arrays and display
# their elements using numpy.nditer()
for a, b in np.nditer([num_1d, num_2d]):
	print("%d:%d" % (a, b),)

    
    
    
    

One dimensional array:
[0 1 2 3 4 5 6]

Two dimensional array:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
0:0
1:1
2:2
3:3
4:4
5:5
6:6
0:7
1:8
2:9
3:10
4:11
5:12
6:13
0:14
1:15
2:16
3:17
4:18
5:19
6:20


In [9]:
   #   2) write a code  to check wheather a Numpy Array contains a specificed rows.

   
     # programs:-
    
    

        
num = np.arange(20)
arr1 = np.reshape(num, [4, 5])
print("Original array:")
print(arr1)
print([0, 1, 2, 3, 4] in arr1.tolist())
print([0, 1, 2, 3, 5] in arr1.tolist())
print([15, 16, 17, 18, 19] in arr1.tolist())




Original array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
True
False
True


In [4]:
    # 3) write a code to pandas code to create & display a dataframe from a specificed dictionary data which 
     # has index labels.
        
        # program :-
 
     
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print(df)
 
 
 

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


In [2]:
# 4) write a code pasands code to create dataframe dict of narray/Lists.


# programe :-

# Python code demonstrate creating
# DataFrame from dict narray / lists
# By default addresses.

import pandas as pd

# initialise data of lists.
data = {'Category':['Array', 'Stack', 'Queue'],
		'Marks':[20, 21, 19]}

# Create DataFrame
df = pd.DataFrame(data)

# Print the output.
print(df )




  Category  Marks
0    Array     20
1    Stack     21
2    Queue     19


In [1]:
    # 5)  write a code to create pandas Dataframe using List of lists .
    
    # program :-
    
    # Import pandas library
import pandas as pd

# initialize list of lists
data = [['DS', 'Linked_list', 10], ['DS', 'Stack', 9], ['DS', 'Queue', 7],
		['Algo', 'Greedy', 8], ['Algo', 'DP', 6], ['Algo', 'BackTrack', 5], ]

# Create the pandas DataFrame
df = pd.DataFrame(data, columns = ['Category', 'Name', 'Marks'])

# print dataframe.
print(df )

    

  Category         Name  Marks
0       DS  Linked_list     10
1       DS        Stack      9
2       DS        Queue      7
3     Algo       Greedy      8
4     Algo           DP      6
5     Algo    BackTrack      5


In [ ]:
   #    ****THANK YOU****